### PR TITLE
feat: motor rotation accurately

### PR DESCRIPTION
**Pull request by iamatulsingh**

### CODE REVIEW

**Review by JurajNyiri — CHANGES_REQUESTED** [review]
Thank you for your contribution. 
Please add unit test coverage for each new function.

**Comment by iamatulsingh** [comment]
> Thank you for your contribution. Please add unit test coverage for each new function.

Its weird that 47 test cases (out of total 47 test cases ) passed but still coverage is 96% for __init__.py

**Comment by JurajNyiri** [comment]
Hello, that is ok. We just need to cover new functions added in this pr. The format function is not unit tested for obvious reasons.

**Comment by iamatulsingh** [comment]
> Hello, that is ok. We just need to cover new functions added in this pr. The format function is not unit tested for obvious reasons.

Just added

**Review by JurajNyiri — APPROVED** [review]

**Comment by JurajNyiri** [comment]
Thank you! I will publish this when I get to computer.

**Pull request merged**
